PUT http://localhost:9012/api/v2/orderItems/modify
Content-Type: application/json

{
    "orderId": "1",
    "ItemName": "pant",
    "Rate": "100",
    "Pcs": "2",
    "Amount": "200",
    "pk": 1
  }
