PUT http://localhost:9012/api/v3/orders/modify
Content-Type: application/json

{
    "CustomerName": "Ram",
    "CustomerMobile": "9876543210",
    "OrderDate": "2023-10-01",
    "OrderNumber": "ORD008",
    "orderId": "1",
    "pk": 3
  }
